action = "http://axemod.userscreen.net";
actionName = "Website";
author = "AXE-Team";
description = "Bugtracker: https://github.com/AXEmod/AXE/issues";
dir = "@AXE";
hideName = 0;
hidePicture = 0;
logo = "\axe_main\data\logo_normal.paa";
logoOver = "\axe_main\data\logo_over.paa";
logoSmall = "\axe_main\data\logo_small.paa";
name = "Arma eXtended Environment 1.2.0";
overview = "Arma eXtended Environment, also known as AXE, adds a variety of additional functions and features on top of Arma3, CBA and the ACE3 framework.";
overviewFootnote = "&lt;br /&gt;&lt;br /&gt;&lt;t color='#999999'&gt;Arma eXtended Environment - Copyright &copy; 2019 by AXE-Team&lt;t /&gt;";
overviewPicture = "\axe_main\data\picture.paa";
picture = "\axe_main\data\picture.paa";
tooltip = "AXE";
tooltipOwned = "AXE";
