// MOD MAIN/PREFIX

#define MAINPREFIX z
#define PREFIX axe

// MOD VERSION

#include "script_version.hpp"

#define VERSION MAJOR.MINOR.PATCHLVL.BUILD
#define VERSION_AR MAJOR,MINOR,PATCHLVL,BUILD

// MINIMAL REQUIRED VERSIONS
// ARMA, CBA, ACE

#define REQUIRED_VERSION 1.94
#define REQUIRED_CBA_VERSION {3,12,2}
#define REQUIRED_ACE_VERSION {3,12,6}
